name: 'autotag-techs-action'
description: 'Automatically detect technologies used in a repository and create repository topics based on Simple Icons API'
author: 'SKRTEEEEEE'
branding:
  icon: 'package'
  color: 'blue'

inputs:
  token:
    description: 'GitHub token with repository write permissions (optional, uses GITHUB_TOKEN by default)'
    required: false
  full:
    description: 'Include all detected technologies or only those available in the API'
    required: false
    default: 'false'

outputs:
  detected_techs:
    description: 'List of technologies detected in the repository'
  created_topics:
    description: 'List of topics created in the repository'

runs:
  using: 'node20'
  main: 'dist/index.js'
